### ISSUE TITLE
package conflict

### ISSUE THREAD

**Issue by ghost** [daohoangson/flutter-tinhte_demo#2]
[flutter-tinhte_demo] flutter packages get
Running "flutter packages get" in flutter-tinhte_demo...        
Because every version of flutter_test from sdk depends on async 2.0.8 and every version of tinhte_api from path depends on async ^2.1.0, flutter_test from sdk is incompatible with tinhte_api from path.

So, because tinhte_demo depends on both tinhte_api from path and flutter_test any from sdk, version solving failed.
pub get failed (1)
exit code 1

**Comment by daohoangson** [comment]
Which version of `flutter` are you using?
