### ISSUE TITLE
Try it out with my own forum

### ISSUE THREAD

**Issue by JulianD** [daohoangson/flutter-tinhte_demo#21]
I just came across this repository! Very interesting!

Do you think it would be possible to modify it to work with my own forum?

I mean, like changing the API endpoint or something?

**Comment by daohoangson** [comment]
Should be possible. This repo uses `git-crypt` to protect the credentials and config, if you fork it and replace those encrypted files with your own then it should work.

On the server side, the app connects to a XenForo 1 installation with [bdApi](https://github.com/xfrocks/bdApi) installed so you will need those on your server. The demo makes use of a few priority api so I expect something will break but it should work well enough for the standard stuff (search, forum list, forum view, thread view, etc.)
